package com.example.superheroapp.util

object Const {
    const val BASE_URL = "https://akabab.github.io/superhero-api/api/"
    const val APP_DATABASE = "app_database"
    const val HEROES_TABLE = "heroes_table"
    const val ALL_HEROES = ""
    const val MARVEL_COMICS = "Marvel Comics"
    const val MARVEL_COMICS_IMAGE_URL = "https://cdn0.iconfinder.com/data/icons/logos-21/40/Marvel-128.png"
    const val DARK_HORSE_COMICS = "Dark Horse Comics"
    const val DARK_HORSE_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/ru/thumb/b/bf/Dark_Horse_Comics_Logo.svg/128px-Dark_Horse_Comics_Logo.svg.png"
    const val GEORGE_LUCAS_COMICS = "George Lucas"
    const val GEORGE_LUCAS_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Star_wars2.svg/128px-Star_wars2.svg.png"
    const val DC_COMICS = "DC Comics"
    const val DC_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/DC_Comics_logo.svg/128px-DC_Comics_logo.svg.png"
    const val ABC_STUDIOS_COMICS = "ABC Studios"
    const val ABC_STUDIOS_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/ABC_Studios_logo.svg/128px-ABC_Studios_logo.svg.png"
    const val NBC_COMICS = "NBC - Heroes"
    const val NBC_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/NBC_logo.svg/128px-NBC_logo.svg.png"
    const val STAR_TREK_COMICS = "Star Trek"
    const val STAR_TREK_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Emblem.svg/128px-Emblem.svg.png"
    const val SYFY_COMICS = "SyFy"
    const val SYFY_COMICS_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Syfy_france.svg/128px-Syfy_france.svg.png"
    const val IDW_COMICS = "IDW Publishing"
    const val IDW_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/IDW_Publishing_logo.svg/128px-IDW_Publishing_logo.svg.png"
    const val ICON_COMICS = "Icon Comics"
    const val ICON_IMAGE_URL = "https://static.wikia.nocookie.net/marveldatabase/images/1/1f/Icon_Comics.png/revision/latest/smart/width/128/height/128?cb=20110604021058"
    const val IMAGE_COMICS = "Image Comics"
    const val IMAGE_IMAGE_URL = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Image_Comics_logo.svg/128px-Image_Comics_logo.svg.png"
}
